---
- hosts: all
  sudo: yes
  vars:
    redis_version: 2.8.9
  tasks:
  - name: install node
    yum: update_cache=yes name={{ item }} state=present enablerepo=epel
    with_items:
      - nodejs
      - npm
  # - name: remove src if exists
  #   file: path=/src/ state=absent

  - name: create src
    file: path=/src state=directory

  - name: unzip and copy to destination
    unarchive: src='../pagecountapp-master.zip' dest='/src/' copy='yes'

  - name: npm install
    npm: path=/src/pagecountapp-master

  - name: run main.js
    command: node /src/pagecountapp-master/main.js


  # - name: download redis
  #   get_url: url=http://download.redis.io/releases/redis-{{ redis_version }}.tar.gz dest=/tmp/
  #
  # - name: extract redis
  #   command: tar zxf /tmp/redis-{{ redis_version }}.tar.gz -C /usr/local/src/
  #
  # - name: make redis
  #   # command: make install --directory=/usr/local/src/redis-{{ redis_version }}
